
services:
  # ROS 2 Jazzy + Gazebo Harmonic + PX4 Autopilot + NoVNC
  px4-sitl:
    build:
      context: .
      dockerfile: px4-sitl.Dockerfile
    image: erdemuysalx/px4-sitl:latest
    container_name: px4_sitl 
    privileged: true
    stdin_open: true
    tty: true
    
    volumes:
      - ./ros2_ws:/root/ros2_ws:rw
      - ./worlds:/root/worlds:rw
      - ./scripts:/root/scripts:rw
      - ./worlds/obstacle_course.sdf:/root/PX4-Autopilot/Tools/simulation/gz/worlds/obstacle_course.sdf:ro
      - ./docs:/root/docs:rw
      - ./media:/root/media:rw

    environment:
      - DISPLAY=:1
      # - DISPLAY=${DISPLAY}
      # - PX4_GZ_WORLD=default
      - GZ_SIM_RESOURCE_PATH=/root/worlds:/root/PX4-Autopilot/Tools/simulation/gz/worlds:/root/PX4-Autopilot/Tools/simulation/gz/models

    ports:
      - "5901:5901"
      - "6080:6080"
      - "14550:14550/udp"
      - "18570:18570/udp"
    
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s